name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: aclocal
      run: aclocal --force -I m4 --install
    - name: autoconf
      run: autoconf --force
    - name: libtoolize
      run: libtoolize --force
    - name: automake
      run: automake --add-missing
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
